"""Builds telemetry_fixture.cpp and writes simulation/tests/fixtures/telemetry.leika, the recording the
simulation's loader is tested against, encoded by the firmware's own nanopb types.

Run from the repo root: uv run --no-project python esp32/test/host/export_telemetry_fixture.py
Needs the nanopb sources generated by esp32/scripts/compile_protos.py (any firmware build) and g++ ($CXX).
"""
import os
import subprocess
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", "..", ".."))
OUT = os.path.join(REPO, "simulation", "tests", "fixtures", "telemetry.leika")
INCLUDES = [os.path.join(HERE, "stubs"), os.path.join(REPO, "submodules", "nanopb")]
# After the system headers: the firmware's features.h would otherwise shadow the glibc <features.h> that <cmath> includes.
FIRMWARE_INCLUDES = [os.path.join(REPO, "esp32", "include"), os.path.join(REPO, "esp32", "src")]
SOURCES = [os.path.join(REPO, "submodules", "nanopb", name) for name in ("pb_common.c", "pb_encode.c", "pb_decode.c")]
SOURCES += [os.path.join(REPO, "esp32", "src", "platform_shared", name)
            for name in ("api.pb.c", "filesystem.pb.c", "message.pb.c")]


def main() -> None:
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with tempfile.TemporaryDirectory() as workdir:
        binary = os.path.join(workdir, "telemetry_fixture.exe")
        subprocess.run([os.environ.get("CXX", "g++"), "-std=gnu++20", "-O0", *[f"-I{p}" for p in INCLUDES],
                        *[f"-idirafter{p}" for p in FIRMWARE_INCLUDES], os.path.join(HERE, "telemetry_fixture.cpp"), *SOURCES, "-o", binary], check=True)
        subprocess.run([binary, OUT], check=True)
    print(OUT)


if __name__ == "__main__":
    main()
