"""Builds and runs the firmware's host test programs: uv run --with pytest pytest esp32/test/host

Needs the nanopb headers generated by esp32/scripts/compile_protos.py and a C++20 compiler ($CXX, or g++).
They build with -Ofast, as the firmware does, since its finite-math assumptions change what code does.
Each program prints its failures and exits non-zero when any check fails.
"""
import os
import subprocess

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", "..", ".."))
INCLUDES = [os.path.join(HERE, "stubs"), os.path.join(REPO, "submodules", "nanopb")]
# After the system headers: the firmware's features.h would otherwise shadow the glibc <features.h> that <cmath> includes.
FIRMWARE_INCLUDES = [os.path.join(REPO, "esp32", "include"), os.path.join(REPO, "esp32", "src")]


NANOPB = [os.path.join(REPO, "submodules", "nanopb", name) for name in ("pb_common.c", "pb_encode.c", "pb_decode.c")]
API_PROTO = os.path.join(REPO, "esp32", "src", "platform_shared", "api.pb.c")
MESSAGE_PROTO = os.path.join(REPO, "esp32", "src", "platform_shared", "message.pb.c")
FILESYSTEM_PROTO = os.path.join(REPO, "esp32", "src", "platform_shared", "filesystem.pb.c")

# Each program with the sources it links besides itself.
PROGRAMS = {
    "factory_network_test.cpp": [],
    "motion_inbox_test.cpp": [],
    "motion_service_test.cpp": [os.path.join(REPO, "esp32", "src", "motion.cpp")],
    "servo_output_test.cpp": [],
    "servo_settings_test.cpp": [*NANOPB, API_PROTO],
    "servo_controller_test.cpp": [*NANOPB, API_PROTO],
    "i2c_bus_test.cpp": [],
    "pca9685_test.cpp": [],
    "sleep_test.cpp": [],
    "settings_persistence_test.cpp": [*NANOPB, API_PROTO],
    "robot_settings_test.cpp": [*NANOPB, API_PROTO, MESSAGE_PROTO, FILESYSTEM_PROTO,
                                os.path.join(REPO, "esp32", "src", "robot_service.cpp")],
    "ws_origin_test.cpp": [],
    "app_network_settings_test.cpp": [],
    "dns_reply_test.cpp": [],
    "imu_math_test.cpp": [],
    "critical_damper_test.cpp": [],
    "madgwick_test.cpp": [],
    "imu_drivers_test.cpp": [],
    "imu_test.cpp": [*NANOPB, API_PROTO],
    "spsc_ring_test.cpp": [],
    "stand_compensation_test.cpp": [],
    "telemetry_test.cpp": [*NANOPB, API_PROTO, MESSAGE_PROTO, FILESYSTEM_PROTO],
}


@pytest.mark.parametrize("program", PROGRAMS)
def test_host_program(program, tmp_path):
    binary = str(tmp_path / (program + ".exe"))
    subprocess.run([os.environ.get("CXX", "g++"), "-std=gnu++20", "-Ofast", *[f"-I{p}" for p in INCLUDES],
                    *[f"-idirafter{p}" for p in FIRMWARE_INCLUDES], os.path.join(HERE, program), *PROGRAMS[program], "-o", binary], check=True)
    result = subprocess.run([binary], capture_output=True, text=True, cwd=tmp_path)
    assert result.returncode == 0, result.stdout
