"""Builds and runs factory_network_test.cpp on the host: uv run --with pytest pytest esp32/test/host

Needs the nanopb headers generated by esp32/scripts/compile_protos.py and a C++20 compiler ($CXX, or g++).
"""
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", "..", ".."))


def test_factory_network_merge(tmp_path):
    binary = str(tmp_path / "factory_network_test.exe")
    includes = [os.path.join(REPO, "esp32", "include"), os.path.join(REPO, "esp32", "src"),
                os.path.join(REPO, "submodules", "nanopb")]
    sources = [os.path.join(HERE, "factory_network_test.cpp"),
               os.path.join(REPO, "esp32", "src", "platform_shared", "api.pb.c"),
               os.path.join(REPO, "submodules", "nanopb", "pb_common.c")]
    subprocess.run([os.environ.get("CXX", "g++"), "-std=gnu++20", *[f"-I{p}" for p in includes], "-x", "c++",
                    *sources, "-o", binary], check=True)
    result = subprocess.run([binary], capture_output=True, text=True)
    assert result.returncode == 0, result.stdout
