"""Packs animations/*.json into esp32/include/animation/builtin_clips.h, the clips embedded in the firmware.

Run by pre_build.py after the protocol is compiled, and standalone: python esp32/scripts/pack_animations.py
Ported from the Hexapod's pack script, which writes LittleFS files instead: embedded clips arrive with every firmware
update, over the air too. The generated animation_pb2 module lands under .pio, so nothing is written into the source.
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "esp32" / "include" / "animation" / "builtin_clips.h"


def animation_module():
    out = ROOT / ".pio" / "animation_proto"
    out.mkdir(parents=True, exist_ok=True)
    proto = ROOT / "platform_shared" / "animation.proto"
    module = out / "animation_pb2.py"
    if not module.exists() or module.stat().st_mtime < proto.stat().st_mtime:
        subprocess.run([sys.executable, "-m", "grpc_tools.protoc", f"-I{proto.parent}", f"--python_out={out}",
                        str(proto)], check=True)
    sys.path.insert(0, str(out))
    import animation_pb2
    return animation_pb2


def pack(src_dir: Path = ROOT / "animations", out: Path = OUT) -> int:
    from google.protobuf import json_format
    pb = animation_module()
    clips = []
    for src in sorted(src_dir.glob("*.json")):
        msg = json_format.Parse(src.read_text(encoding="utf-8"), pb.Animation())
        if msg.schema != 1 or not msg.keyframes:
            raise SystemExit(f"{src.name}: schema must be 1 and keyframes non-empty")
        if msg.name != src.stem:
            raise SystemExit(f"{src.name}: name '{msg.name}' must equal the file stem")
        clips.append((msg.name, msg.SerializeToString()))
    if not clips:
        raise SystemExit(f"no clips in {src_dir}")
    lines = [
        "// Generated by esp32/scripts/pack_animations.py from animations/*.json; do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace anim {",
        "",
        "struct BuiltinClip {",
        "    const char *name;",
        "    const uint8_t *data;",
        "    size_t size;",
        "};",
        "",
    ]
    for name, data in clips:
        body = ", ".join(f"0x{b:02x}" for b in data)
        lines.append(f"inline constexpr uint8_t BUILTIN_{name.replace('-', '_')}[] = {{{body}}};")
    lines += ["", "inline constexpr BuiltinClip BUILTIN_CLIPS[] = {"]
    lines += [f'    {{"{name}", BUILTIN_{name.replace("-", "_")}, sizeof(BUILTIN_{name.replace("-", "_")})}},'
              for name, _ in clips]
    lines += ["};", "", "}  // namespace anim", ""]
    text = "\n".join(lines)
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
    print(f"animations: packed {len(clips)} clip(s) into {out.relative_to(ROOT)}")
    return len(clips)


if __name__ == "__main__":
    pack()
