spot:
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - motor_front_left_hip
          - motor_front_left_upper_leg
          - motor_front_left_lower_leg
          - motor_front_right_hip
          - motor_front_right_upper_leg
          - motor_front_right_lower_leg
          - motor_back_left_hip
          - motor_back_left_upper_leg
          - motor_back_left_lower_leg
          - motor_back_right_hip
          - motor_back_right_upper_leg
          - motor_back_right_lower_leg

      gains:
        motor_front_left_hip        : {p: 180, d: 0.9, i: 20}
        motor_front_left_upper_leg  : {p: 180, d: 0.9, i: 20}
        motor_front_left_lower_leg  : {p: 180, d: 0.9, i: 20}
        motor_front_right_hip       : {p: 180, d: 0.9, i: 20}
        motor_front_right_upper_leg : {p: 180, d: 0.9, i: 20}
        motor_front_right_lower_leg : {p: 180, d: 0.9, i: 20}
        motor_back_left_hip         : {p: 180, d: 0.9, i: 20}
        motor_back_left_upper_leg   : {p: 180, d: 0.9, i: 20}
        motor_back_left_lower_leg   : {p: 180, d: 0.9, i: 20}
        motor_back_right_hip        : {p: 180, d: 0.9, i: 20}
        motor_back_right_upper_leg  : {p: 180, d: 0.9, i: 20}
        motor_back_right_lower_leg  : {p: 180, d: 0.9, i: 20}