"""The robot's protocol classes, generated by gen_protos.py.

protoc's Python output imports its siblings as top-level modules (import api_pb2), so this folder goes on the path.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import message_pb2  # noqa: E402

__all__ = ["message_pb2"]
