/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PLATFORM_SHARED_EXAMPLE_PB_H_INCLUDED
#define PB_PLATFORM_SHARED_EXAMPLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _IMUType {
    IMUType_IMU_NONE = 0,
    IMUType_IMU_ACCEL = 1,
    IMUType_IMU_GYRO = 2
} IMUType;

/* Struct definitions */
typedef struct _IMUReport {
    IMUType type;
    double x_val;
} IMUReport;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _IMUType_MIN IMUType_IMU_NONE
#define _IMUType_MAX IMUType_IMU_GYRO
#define _IMUType_ARRAYSIZE ((IMUType)(IMUType_IMU_GYRO+1))

#define IMUReport_type_ENUMTYPE IMUType


/* Initializer values for message structs */
#define IMUReport_init_default                   {_IMUType_MIN, 0}
#define IMUReport_init_zero                      {_IMUType_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define IMUReport_type_tag                       1
#define IMUReport_x_val_tag                      2

/* Struct field encoding specification for nanopb */
#define IMUReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, DOUBLE,   x_val,             2)
#define IMUReport_CALLBACK NULL
#define IMUReport_DEFAULT NULL

extern const pb_msgdesc_t IMUReport_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define IMUReport_fields &IMUReport_msg

/* Maximum encoded size of messages (where known) */
#define IMUReport_size                           11
#define PLATFORM_SHARED_EXAMPLE_PB_H_MAX_SIZE    IMUReport_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
