"""Generate golden vectors that pin the firmware's C++ port of the spot_pico kinematics, the
residual-policy baseline gait and the policy inference code to this Python.

The firmware side (esp32/include/spot_pico/*.h and the infer() emitted by export_policy.py) is tested
against the headers written here by `pio test -e native`. Regenerate after changing
firmware_gait.py, linkage.py, gait_coef.json or the exporter:

  uv run python export_golden.py            # rewrite the headers
  uv run python export_golden.py --check    # exit 1 if a header is stale (used in CI)
"""

import argparse
import math
import os
import sys

import numpy as np

from src.robot import firmware_gait as fg
from src.resources.spot_pico import linkage
from export_policy import np_infer, render_header

TEST_DIR = os.path.join(os.path.dirname(__file__), "..", "esp32", "test")
OUT = os.path.join(TEST_DIR, "test_spot_pico", "golden.h")
POLICY_FIXTURE = os.path.join(TEST_DIR, "fixtures", "policy", "leika_policy.h")
WALK_NN_GOLDEN = os.path.join(TEST_DIR, "test_walk_nn", "golden_walk_nn.h")
CONTROL_DT = 0.01

GAIT_COMMANDS = [
    (0.05, 0.0, 0.0),
    (-0.03, 0.0, 0.0),
    (0.0, 0.025, 0.0),
    (0.0, 0.0, 0.8),
    (0.04, -0.015, -0.5),
    (0.0, 0.0, 0.0),
]
GAIT_STEPS = 120
GAIT_SAMPLE_EVERY = 6


def carr(name, values):
    flat = np.asarray(values, dtype=float).ravel()
    body = ",\n    ".join(", ".join(f"{v:.9e}f" for v in flat[i:i + 6]) for i in range(0, flat.size, 6))
    return f"static const float {name}[{flat.size}] = {{\n    {body}}};\n"


def iarr(name, values):
    flat = [int(v) for v in np.asarray(values).ravel()]
    return f"static const int {name}[{len(flat)}] = {{{', '.join(map(str, flat))}}};\n"


def ik_cases(rng):
    targets, legs, angles = [], [], []
    cfg = fg.SpotPicoKinConfig()
    for leg, name in enumerate(fg.LEG_NAMES):
        for spread in (0.0, 0.006, 0.012, 0.012, 0.012, 0.03):
            tgt = fg.DEFAULT_FEET[leg] + rng.uniform(-spread, spread, 3)
            legs.append(leg)
            targets.append(tgt)
            angles.append(fg.leg_ik(cfg, name, tgt))
    return np.array(legs), np.array(targets), np.array(angles)


def fk_cases(rng):
    legs, qs, feet = [], [], []
    for leg, name in enumerate(fg.LEG_NAMES):
        for _ in range(4):
            q = rng.uniform(-0.6, 0.6, 3)
            legs.append(leg)
            qs.append(q)
            feet.append(fg.leg_fk(name, q))
    return np.array(legs), np.array(qs), np.array(feet)


def linkage_cases():
    rows = []
    for tibia_deg in (-50, -30, -10, 0, 15, 35):
        for femur_deg in (-20, 0, 25):
            t, f = math.radians(tibia_deg), math.radians(femur_deg)
            rows.append((t, f, linkage.servo_from_tibia(t, f)))
    return np.array(rows)


def gait_cases():
    """Replays QuadrupedMjEnv._action_to_joints with a zero residual."""
    phases, feet, joints = [], [], []
    kin = fg.Kinematics()
    for cmd in GAIT_COMMANDS:
        gait = fg.GaitState()
        fg.set_mode(gait, fg.TROT)
        gc = fg.GaitController()
        body = fg.BodyState()
        for step in range(GAIT_STEPS):
            fg.analytic_gait_action(np.array(cmd), gait)
            gc.advance_phase(gait, CONTROL_DT)
            gc.generate_feet(gait, body)
            if step % GAIT_SAMPLE_EVERY == GAIT_SAMPLE_EVERY - 1:
                phases.append(gc.phase)
                feet.append(body.feet.copy())
                joints.append(kin.inverse_kinematics(body))
    return np.array(phases), np.array(feet), np.array(joints)


def render():
    rng = np.random.default_rng(7)
    ik_legs, ik_targets, ik_angles = ik_cases(rng)
    fk_legs, fk_q, fk_feet = fk_cases(rng)
    link = linkage_cases()
    phases, feet, joints = gait_cases()
    c = fg.GAIT_COEF
    samples = GAIT_STEPS // GAIT_SAMPLE_EVERY

    out = [
        "#pragma once\n",
        "// Auto-generated by simulation/export_golden.py - DO NOT EDIT.\n",
        "// Golden vectors from the Python spot_pico kinematics and baseline gait.\n\n",
        "namespace golden {\n\n",
        f"constexpr int IK_CASES = {len(ik_legs)};\n",
        iarr("IK_LEG", ik_legs),
        carr("IK_TARGET", ik_targets),
        carr("IK_ANGLES", ik_angles),
        f"\nconstexpr int FK_CASES = {len(fk_legs)};\n",
        iarr("FK_LEG", fk_legs),
        carr("FK_Q", fk_q),
        carr("FK_FOOT", fk_feet),
        f"\nconstexpr int LINKAGE_CASES = {len(link)};\n",
        carr("LINKAGE_TIBIA_FEMUR_SERVO", link),
        "\n",
        carr("DEFAULT_FEET", fg.DEFAULT_FEET),
        carr("STAND_POSE", fg.Kinematics().inverse_kinematics(fg.BodyState())),
        f"\nconstexpr float CONTROL_DT = {CONTROL_DT}f;\n",
        f"constexpr int GAIT_COMMANDS = {len(GAIT_COMMANDS)};\n",
        f"constexpr int GAIT_STEPS = {GAIT_STEPS};\n",
        f"constexpr int GAIT_SAMPLE_EVERY = {GAIT_SAMPLE_EVERY};\n",
        f"constexpr int GAIT_SAMPLES = {samples};\n",
        carr("GAIT_CMD", GAIT_COMMANDS),
        "// gain_x, gain_y, gain_yaw, speed_base, speed_slope, step_height, step_depth\n",
        carr("GAIT_COEF", [c["gain_x"], c["gain_y"], c["gain_yaw"], c["speed_base"], c["speed_slope"],
                           c["step_height"], c["step_depth"]]),
        carr("GAIT_PHASE", phases),
        carr("GAIT_FEET", feet),
        carr("GAIT_JOINTS", joints),
        "\n} // namespace golden\n",
    ]
    return "".join(out)


def render_policy_fixture():
    """A small synthetic network in the exported header format, so the firmware's infer() is tested
    without committing a trained policy. Inputs far outside the normalization range exercise both the
    observation and the action clipping."""
    net = fixture_network()
    rng = np.random.default_rng(12)
    layers, mean, var, clip, eps = net
    test_obs = rng.normal(mean, np.sqrt(var))
    test_obs[:6] = mean[:6] + 50.0 * np.sqrt(var[:6])
    test_act = np_infer(test_obs, *net)
    return render_header(layers, mean, var, clip, eps, fg.GAIT_COEF, test_obs.astype(np.float32),
                         test_act.astype(np.float32), "synthetic test fixture (simulation/export_golden.py)")


def fixture_network():
    rng = np.random.default_rng(11)
    widths = [38, 16, 8, 12]
    layers = [(rng.normal(0, 1 / np.sqrt(i), (o, i)), rng.normal(0, 0.1, o)) for i, o in zip(widths, widths[1:])]
    layers[-1] = (layers[-1][0] * 1.5, layers[-1][1])
    mean, var = rng.normal(0, 0.5, 38), rng.uniform(0.01, 2.0, 38)
    return layers, mean, var, 10.0, 1e-8


WALK_NN_JOYSTICK = (0.7, 0.0, -0.4)  # ly, lx, rx
WALK_NN_TICKS = 60


def render_walk_nn():
    """Drives the real QuadrupedMjEnv.step with the fixture network and a level, motionless IMU, so
    the firmware's WalkNNState is pinned to the env's control pipeline (observation layout and
    history, phase clock, command scaling, residual application) independently of the physics."""
    from src.envs import quadruped_mj_env as qe

    net = fixture_network()
    ly, lx, rx = WALK_NN_JOYSTICK
    cmd = (ly * (qe.CMD_VX[1] if ly >= 0 else -qe.CMD_VX[0]), -lx * qe.CMD_VY[1], -rx * qe.CMD_YAW[1])
    env = qe.QuadrupedMjEnv(command=cmd)
    env.sim.base_quat = lambda: np.array([1.0, 0.0, 0.0, 0.0])
    env.sim.gyro = lambda: np.zeros(3)
    env.sim.step_physics = lambda n=None: None
    obs, _ = env.reset()
    feet, joints, actions = [], [], []
    for _ in range(WALK_NN_TICKS):
        action = np_infer(obs.astype(np.float64), *net)
        obs, *_ = env.step(action)
        actions.append(action)
        feet.append(env.body.feet.copy())
        joints.append(env.prev_joint_cmd.copy())
    saturated = float(np.mean(np.abs(np.array(actions)) >= 1.0))
    return "".join([
        "#pragma once\n",
        "// Auto-generated by simulation/export_golden.py - DO NOT EDIT.\n",
        "// QuadrupedMjEnv.step replayed with the fixture policy and a level, motionless IMU.\n",
        f"// {saturated:.0%} of the actions are saturated.\n\n",
        "namespace golden_walk_nn {\n\n",
        f"constexpr int TICKS = {WALK_NN_TICKS};\n",
        carr("JOYSTICK", WALK_NN_JOYSTICK),
        "// per tick: spot_pico base-frame foot targets after the residual, legs fr, fl, rr, rl\n",
        carr("FEET", feet),
        "// per tick: commanded joint angles (rad), legs fr, fl, rr, rl x (hip, femur, tibia)\n",
        carr("JOINTS", joints),
        "\n} // namespace golden_walk_nn\n",
    ])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if a committed header is stale")
    args = ap.parse_args()
    outputs = {
        os.path.abspath(OUT): render(),
        os.path.abspath(POLICY_FIXTURE): render_policy_fixture(),
        os.path.abspath(WALK_NN_GOLDEN): render_walk_nn(),
    }
    if args.check:
        stale = [p for p, text in outputs.items()
                 if not os.path.exists(p) or open(p, encoding="utf-8").read() != text]
        for p in stale:
            print(f"{p} is stale; run `uv run python export_golden.py`", file=sys.stderr)
        if stale:
            sys.exit(1)
        print("golden headers are up to date")
        return
    for path, text in outputs.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
