"""Generates MuJoCo scenes for Spot Micro and Yertle from the web app's URDF models (app/static).

The web app's simulation drives them like the Pico's hand-made scene: a floor, a free-floating
base named "root", a "foot_<leg>" site at each toe, an "imu" site on the base, and one position
actuator per leg joint, named after the joint. Meshes are referenced by file name and supplied at
load time from the app's own files, so they are not copied here.
Run from simulation/: uv run python generate_scenes.py
tests/test_generated_scenes.py fails when a committed scene is out of date.
"""
import os
import re

import mujoco
import xacro

HERE = os.path.dirname(os.path.abspath(__file__))
STATIC = os.path.normpath(os.path.join(HERE, "..", "app", "static"))

# Servo stand-ins are estimates, not measurements: position servos with the given stiffness
# (N m/rad) and torque limit (N m), and joint damping chosen for a stable simulation.
ROBOTS = {
    "spot_micro": dict(
        source="spot_micro.urdf.xacro",
        mesh_dir=None,  # its collision shapes are all boxes and spheres
        toes={"fl": "front_left_toe_link", "fr": "front_right_toe_link",
              "rl": "rear_left_toe_link", "rr": "rear_right_toe_link"},
        placeholder_inertia=None,
        kp=30.0, force=3.0,
    ),
    "yertle": dict(
        source="yertle.URDF",
        mesh_dir="URDF",
        toes={"fl": "lf_toe", "fr": "rf_toe", "rl": "lb_toe", "rr": "rb_toe"},
        # Its URDF inertia tensors are placeholders (not positive definite); its masses are kept and
        # each tensor becomes that of a solid sphere of this radius (m), heavier parts larger.
        placeholder_inertia=lambda mass: 0.08 if mass >= 1 else 0.03,
        kp=20.0, force=2.0,
    ),
}
JOINT_DAMPING = 0.1
JOINT_ARMATURE = 0.01


def scene_path(robot: str) -> str:
    return os.path.join(HERE, "src", "resources", robot, "scene.xml")


def mesh_assets(robot: str) -> dict[str, bytes]:
    mesh_dir = ROBOTS[robot]["mesh_dir"]
    if not mesh_dir:
        return {}
    folder = os.path.join(STATIC, mesh_dir)
    return {name: open(os.path.join(folder, name), "rb").read()
            for name in sorted(os.listdir(folder)) if name.endswith(".stl")}


def _source(robot: str) -> str:
    path = os.path.join(STATIC, ROBOTS[robot]["source"])
    return xacro.process_file(path).toxml() if path.endswith(".xacro") else open(path, encoding="utf8").read()


def urdf_mass(robot: str) -> float:
    return sum(float(m) for m in re.findall(r'<mass value="([^"]+)"', _source(robot)))


def _sphere_inertia(inertial: re.Match, radius_of) -> str:
    block = inertial.group(0)
    mass = float(re.search(r'<mass value="([^"]+)"', block).group(1))
    moment = 0.4 * mass * radius_of(mass) ** 2
    tensor = f'<inertia ixx="{moment:.6g}" ixy="0" ixz="0" iyy="{moment:.6g}" iyz="0" izz="{moment:.6g}"/>'
    return re.sub(r"<inertia\b[^>]*/>", tensor, block)


def _urdf(robot: str) -> str:
    config = ROBOTS[robot]
    text = _source(robot)
    if config["placeholder_inertia"]:
        text = re.sub(r"<inertial>.*?</inertial>", lambda m: _sphere_inertia(m, config["placeholder_inertia"]),
                      text, flags=re.S)
    # package://<pkg>/<file> becomes the bare file name the mesh assets are keyed by.
    text = re.sub(r'filename="package://[^/"]+/([^"]+)"', r'filename="\1"', text)
    compiler = ('<mujoco><compiler meshdir="meshes/" strippath="false" fusestatic="false" '
                'discardvisual="true" balanceinertia="true" inertiafromgeom="false"/></mujoco>')
    return re.sub(r"(<robot\b[^>]*>)", r"\1" + compiler, text, count=1)


def _spec(robot: str) -> mujoco.MjSpec:
    config = ROBOTS[robot]
    spec = mujoco.MjSpec.from_string(_urdf(robot), assets=mesh_assets(robot))
    base = spec.worldbody.first_body()
    base.add_freejoint(name="root")
    base.add_site(name="imu")
    spec.worldbody.add_geom(name="floor", type=mujoco.mjtGeom.mjGEOM_PLANE, size=[0, 0, 0.05])
    for leg, link in config["toes"].items():
        spec.body(link).add_site(name=f"foot_{leg}")

    for joint in spec.joints:
        if joint.type != mujoco.mjtJoint.mjJNT_HINGE:
            continue
        joint.damping = [JOINT_DAMPING, 0, 0]
        joint.armature = JOINT_ARMATURE
        actuator = spec.add_actuator(name=joint.name, target=joint.name, trntype=mujoco.mjtTrn.mjTRN_JOINT)
        actuator.set_to_position(kp=config["kp"], dampratio=1.0)
        actuator.forcelimited = mujoco.mjtLimited.mjLIMITED_TRUE
        actuator.forcerange = [-config["force"], config["force"]]
    return spec


def generate(robot: str) -> str:
    spec = _spec(robot)
    spec.compile()
    header = (f"<!-- Generated by simulation/generate_scenes.py from app/static/{ROBOTS[robot]['source']};"
              " do not edit.\n     Servo stiffness and torque, joint damping and replaced inertia tensors"
              " are estimates. -->\n")
    xml = spec.to_xml()
    first_line_end = xml.index("\n") + 1 if xml.startswith("<?xml") else 0
    return xml[:first_line_end] + header + xml[first_line_end:]


def main() -> None:
    for robot in ROBOTS:
        path = scene_path(robot)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf8", newline="\n") as f:
            f.write(generate(robot))
        print(f"{robot}: {os.path.relpath(path, HERE)}")


if __name__ == "__main__":
    main()
