// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: platform_shared/imu_report.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'

export const protobufPackage = ''

export interface IMUReport {
    x: number
    y: number
    z: number
    temp: number
    success: boolean
}

function createBaseIMUReport(): IMUReport {
    return { x: 0, y: 0, z: 0, temp: 0, success: false }
}

export const IMUReport: MessageFns<IMUReport> = {
    encode(message: IMUReport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
        if (message.x !== 0) {
            writer.uint32(13).float(message.x)
        }
        if (message.y !== 0) {
            writer.uint32(21).float(message.y)
        }
        if (message.z !== 0) {
            writer.uint32(29).float(message.z)
        }
        if (message.temp !== 0) {
            writer.uint32(37).float(message.temp)
        }
        if (message.success !== false) {
            writer.uint32(40).bool(message.success)
        }
        return writer
    },

    decode(input: BinaryReader | Uint8Array, length?: number): IMUReport {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
        const end = length === undefined ? reader.len : reader.pos + length
        const message = createBaseIMUReport()
        while (reader.pos < end) {
            const tag = reader.uint32()
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 13) {
                        break
                    }

                    message.x = reader.float()
                    continue
                }
                case 2: {
                    if (tag !== 21) {
                        break
                    }

                    message.y = reader.float()
                    continue
                }
                case 3: {
                    if (tag !== 29) {
                        break
                    }

                    message.z = reader.float()
                    continue
                }
                case 4: {
                    if (tag !== 37) {
                        break
                    }

                    message.temp = reader.float()
                    continue
                }
                case 5: {
                    if (tag !== 40) {
                        break
                    }

                    message.success = reader.bool()
                    continue
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break
            }
            reader.skip(tag & 7)
        }
        return message
    },

    fromJSON(object: any): IMUReport {
        return {
            x: isSet(object.x) ? globalThis.Number(object.x) : 0,
            y: isSet(object.y) ? globalThis.Number(object.y) : 0,
            z: isSet(object.z) ? globalThis.Number(object.z) : 0,
            temp: isSet(object.temp) ? globalThis.Number(object.temp) : 0,
            success: isSet(object.success) ? globalThis.Boolean(object.success) : false
        }
    },

    toJSON(message: IMUReport): unknown {
        const obj: any = {}
        if (message.x !== 0) {
            obj.x = message.x
        }
        if (message.y !== 0) {
            obj.y = message.y
        }
        if (message.z !== 0) {
            obj.z = message.z
        }
        if (message.temp !== 0) {
            obj.temp = message.temp
        }
        if (message.success !== false) {
            obj.success = message.success
        }
        return obj
    },

    create<I extends Exact<DeepPartial<IMUReport>, I>>(base?: I): IMUReport {
        return IMUReport.fromPartial(base ?? ({} as any))
    },
    fromPartial<I extends Exact<DeepPartial<IMUReport>, I>>(object: I): IMUReport {
        const message = createBaseIMUReport()
        message.x = object.x ?? 0
        message.y = object.y ?? 0
        message.z = object.z ?? 0
        message.temp = object.temp ?? 0
        message.success = object.success ?? false
        return message
    }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> =
    T extends Builtin ? T
    : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
    : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
    : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> =
    P extends Builtin ? P
    :   P & { [K in keyof P]: Exact<P[K], I[K]> } & {
            [K in Exclude<keyof I, KeysOfUnion<P>>]: never
        }

function isSet(value: any): boolean {
    return value !== null && value !== undefined
}

export interface MessageFns<T> {
    encode(message: T, writer?: BinaryWriter): BinaryWriter
    decode(input: BinaryReader | Uint8Array, length?: number): T
    fromJSON(object: any): T
    toJSON(message: T): unknown
    create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
    fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
