// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.20.3
// source: rest_message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "./typeRegistry";
import { KnownNetworkItem } from "./websocket_message";

export const protobufPackage = "rest_message";

export interface WifiStatus {
  $type: "rest_message.WifiStatus";
  status: number;
  localIp: string;
  macAddress: string;
  rssi: number;
  ssid: string;
  bssid: string;
  channel: number;
  subnetMask: string;
  gatewayIp: string;
  dnsIp1: string;
  dnsIp2?: string | undefined;
}

export interface WifiSettings {
  $type: "rest_message.WifiSettings";
  hostname: string;
  priorityRssi: boolean;
  wifiNetworks: KnownNetworkItem[];
}

function createBaseWifiStatus(): WifiStatus {
  return {
    $type: "rest_message.WifiStatus",
    status: 0,
    localIp: "",
    macAddress: "",
    rssi: 0,
    ssid: "",
    bssid: "",
    channel: 0,
    subnetMask: "",
    gatewayIp: "",
    dnsIp1: "",
    dnsIp2: undefined,
  };
}

export const WifiStatus: MessageFns<WifiStatus, "rest_message.WifiStatus"> = {
  $type: "rest_message.WifiStatus" as const,

  encode(message: WifiStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.localIp !== "") {
      writer.uint32(18).string(message.localIp);
    }
    if (message.macAddress !== "") {
      writer.uint32(26).string(message.macAddress);
    }
    if (message.rssi !== 0) {
      writer.uint32(37).float(message.rssi);
    }
    if (message.ssid !== "") {
      writer.uint32(42).string(message.ssid);
    }
    if (message.bssid !== "") {
      writer.uint32(50).string(message.bssid);
    }
    if (message.channel !== 0) {
      writer.uint32(56).uint32(message.channel);
    }
    if (message.subnetMask !== "") {
      writer.uint32(66).string(message.subnetMask);
    }
    if (message.gatewayIp !== "") {
      writer.uint32(74).string(message.gatewayIp);
    }
    if (message.dnsIp1 !== "") {
      writer.uint32(82).string(message.dnsIp1);
    }
    if (message.dnsIp2 !== undefined) {
      writer.uint32(90).string(message.dnsIp2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WifiStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.localIp = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.macAddress = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.rssi = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ssid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.bssid = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.channel = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.subnetMask = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.gatewayIp = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.dnsIp1 = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.dnsIp2 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WifiStatus {
    return {
      $type: WifiStatus.$type,
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      localIp: isSet(object.localIp) ? globalThis.String(object.localIp) : "",
      macAddress: isSet(object.macAddress) ? globalThis.String(object.macAddress) : "",
      rssi: isSet(object.rssi) ? globalThis.Number(object.rssi) : 0,
      ssid: isSet(object.ssid) ? globalThis.String(object.ssid) : "",
      bssid: isSet(object.bssid) ? globalThis.String(object.bssid) : "",
      channel: isSet(object.channel) ? globalThis.Number(object.channel) : 0,
      subnetMask: isSet(object.subnetMask) ? globalThis.String(object.subnetMask) : "",
      gatewayIp: isSet(object.gatewayIp) ? globalThis.String(object.gatewayIp) : "",
      dnsIp1: isSet(object.dnsIp1) ? globalThis.String(object.dnsIp1) : "",
      dnsIp2: isSet(object.dnsIp2) ? globalThis.String(object.dnsIp2) : undefined,
    };
  },

  toJSON(message: WifiStatus): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.localIp !== "") {
      obj.localIp = message.localIp;
    }
    if (message.macAddress !== "") {
      obj.macAddress = message.macAddress;
    }
    if (message.rssi !== 0) {
      obj.rssi = message.rssi;
    }
    if (message.ssid !== "") {
      obj.ssid = message.ssid;
    }
    if (message.bssid !== "") {
      obj.bssid = message.bssid;
    }
    if (message.channel !== 0) {
      obj.channel = Math.round(message.channel);
    }
    if (message.subnetMask !== "") {
      obj.subnetMask = message.subnetMask;
    }
    if (message.gatewayIp !== "") {
      obj.gatewayIp = message.gatewayIp;
    }
    if (message.dnsIp1 !== "") {
      obj.dnsIp1 = message.dnsIp1;
    }
    if (message.dnsIp2 !== undefined) {
      obj.dnsIp2 = message.dnsIp2;
    }
    return obj;
  },

  create(base?: DeepPartial<WifiStatus>): WifiStatus {
    return WifiStatus.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WifiStatus>): WifiStatus {
    const message = createBaseWifiStatus();
    message.status = object.status ?? 0;
    message.localIp = object.localIp ?? "";
    message.macAddress = object.macAddress ?? "";
    message.rssi = object.rssi ?? 0;
    message.ssid = object.ssid ?? "";
    message.bssid = object.bssid ?? "";
    message.channel = object.channel ?? 0;
    message.subnetMask = object.subnetMask ?? "";
    message.gatewayIp = object.gatewayIp ?? "";
    message.dnsIp1 = object.dnsIp1 ?? "";
    message.dnsIp2 = object.dnsIp2 ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(WifiStatus.$type, WifiStatus);

function createBaseWifiSettings(): WifiSettings {
  return { $type: "rest_message.WifiSettings", hostname: "", priorityRssi: false, wifiNetworks: [] };
}

export const WifiSettings: MessageFns<WifiSettings, "rest_message.WifiSettings"> = {
  $type: "rest_message.WifiSettings" as const,

  encode(message: WifiSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hostname !== "") {
      writer.uint32(10).string(message.hostname);
    }
    if (message.priorityRssi !== false) {
      writer.uint32(16).bool(message.priorityRssi);
    }
    for (const v of message.wifiNetworks) {
      KnownNetworkItem.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WifiSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hostname = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.priorityRssi = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.wifiNetworks.push(KnownNetworkItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WifiSettings {
    return {
      $type: WifiSettings.$type,
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "",
      priorityRssi: isSet(object.priorityRssi) ? globalThis.Boolean(object.priorityRssi) : false,
      wifiNetworks: globalThis.Array.isArray(object?.wifiNetworks)
        ? object.wifiNetworks.map((e: any) => KnownNetworkItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: WifiSettings): unknown {
    const obj: any = {};
    if (message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    if (message.priorityRssi !== false) {
      obj.priorityRssi = message.priorityRssi;
    }
    if (message.wifiNetworks?.length) {
      obj.wifiNetworks = message.wifiNetworks.map((e) => KnownNetworkItem.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<WifiSettings>): WifiSettings {
    return WifiSettings.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WifiSettings>): WifiSettings {
    const message = createBaseWifiSettings();
    message.hostname = object.hostname ?? "";
    message.priorityRssi = object.priorityRssi ?? false;
    message.wifiNetworks = object.wifiNetworks?.map((e) => KnownNetworkItem.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(WifiSettings.$type, WifiSettings);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
