// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: platform_shared/websocket_message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { FileDescriptorProto } from "ts-proto-descriptors";

export const protobufPackage = "";

/** Individual message data types */
export interface IMUData {
  x: number;
  y: number;
  z: number;
  temp: number;
}

export interface IMUCalibrateData {
}

export interface ModeData {
  mode: number;
}

export interface InputData {
}

export interface AnalyticsData {
}

export interface PositionData {
}

export interface AnglesData {
  angles: number[];
}

export interface I2CScanData {
}

export interface PeripheralSettingsData {
}

export interface OTAStatusData {
}

export interface GaitData {
}

export interface ServoStateData {
}

export interface ServoPWMData {
}

export interface WifiSettingsData {
}

export interface SonarData {
}

export interface RSSIData {
  rssi: number;
}

export interface SubscribeNotification {
}

export interface UnsubscribeNotification {
}

/**
 * WebSocket message wrapper
 * Only ONE field will be set at a time (oneof ensures this)
 */
export interface WebsocketMessage {
  subNotif?: SubscribeNotification | undefined;
  unsubNotif?: UnsubscribeNotification | undefined;
  imu?: IMUData | undefined;
  imuCalibrate?: IMUCalibrateData | undefined;
  mode?: ModeData | undefined;
  input?: InputData | undefined;
  analytics?: AnalyticsData | undefined;
  position?: PositionData | undefined;
  angles?: AnglesData | undefined;
  i2cScan?: I2CScanData | undefined;
  peripheralSettings?: PeripheralSettingsData | undefined;
  otaStatus?: OTAStatusData | undefined;
  gait?: GaitData | undefined;
  servoState?: ServoStateData | undefined;
  servoPwm?: ServoPWMData | undefined;
  wifiSettings?: WifiSettingsData | undefined;
  sonar?: SonarData | undefined;
  rssi?: RSSIData | undefined;
}

function createBaseIMUData(): IMUData {
  return { x: 0, y: 0, z: 0, temp: 0 };
}

export const IMUData: MessageFns<IMUData> = {
  encode(message: IMUData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(13).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(21).float(message.y);
    }
    if (message.z !== 0) {
      writer.uint32(29).float(message.z);
    }
    if (message.temp !== 0) {
      writer.uint32(37).float(message.temp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IMUData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIMUData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.x = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.y = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.z = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.temp = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IMUData {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      z: isSet(object.z) ? globalThis.Number(object.z) : 0,
      temp: isSet(object.temp) ? globalThis.Number(object.temp) : 0,
    };
  },

  toJSON(message: IMUData): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.z !== 0) {
      obj.z = message.z;
    }
    if (message.temp !== 0) {
      obj.temp = message.temp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IMUData>, I>>(base?: I): IMUData {
    return IMUData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IMUData>, I>>(object: I): IMUData {
    const message = createBaseIMUData();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.z = object.z ?? 0;
    message.temp = object.temp ?? 0;
    return message;
  },
};

function createBaseIMUCalibrateData(): IMUCalibrateData {
  return {};
}

export const IMUCalibrateData: MessageFns<IMUCalibrateData> = {
  encode(_: IMUCalibrateData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IMUCalibrateData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIMUCalibrateData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): IMUCalibrateData {
    return {};
  },

  toJSON(_: IMUCalibrateData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<IMUCalibrateData>, I>>(base?: I): IMUCalibrateData {
    return IMUCalibrateData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IMUCalibrateData>, I>>(_: I): IMUCalibrateData {
    const message = createBaseIMUCalibrateData();
    return message;
  },
};

function createBaseModeData(): ModeData {
  return { mode: 0 };
}

export const ModeData: MessageFns<ModeData> = {
  encode(message: ModeData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mode !== 0) {
      writer.uint32(8).int32(message.mode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModeData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModeData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModeData {
    return { mode: isSet(object.mode) ? globalThis.Number(object.mode) : 0 };
  },

  toJSON(message: ModeData): unknown {
    const obj: any = {};
    if (message.mode !== 0) {
      obj.mode = Math.round(message.mode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModeData>, I>>(base?: I): ModeData {
    return ModeData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModeData>, I>>(object: I): ModeData {
    const message = createBaseModeData();
    message.mode = object.mode ?? 0;
    return message;
  },
};

function createBaseInputData(): InputData {
  return {};
}

export const InputData: MessageFns<InputData> = {
  encode(_: InputData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InputData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInputData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): InputData {
    return {};
  },

  toJSON(_: InputData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<InputData>, I>>(base?: I): InputData {
    return InputData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InputData>, I>>(_: I): InputData {
    const message = createBaseInputData();
    return message;
  },
};

function createBaseAnalyticsData(): AnalyticsData {
  return {};
}

export const AnalyticsData: MessageFns<AnalyticsData> = {
  encode(_: AnalyticsData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnalyticsData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnalyticsData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): AnalyticsData {
    return {};
  },

  toJSON(_: AnalyticsData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<AnalyticsData>, I>>(base?: I): AnalyticsData {
    return AnalyticsData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AnalyticsData>, I>>(_: I): AnalyticsData {
    const message = createBaseAnalyticsData();
    return message;
  },
};

function createBasePositionData(): PositionData {
  return {};
}

export const PositionData: MessageFns<PositionData> = {
  encode(_: PositionData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PositionData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePositionData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): PositionData {
    return {};
  },

  toJSON(_: PositionData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PositionData>, I>>(base?: I): PositionData {
    return PositionData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PositionData>, I>>(_: I): PositionData {
    const message = createBasePositionData();
    return message;
  },
};

function createBaseAnglesData(): AnglesData {
  return { angles: [] };
}

export const AnglesData: MessageFns<AnglesData> = {
  encode(message: AnglesData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.angles) {
      writer.float(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnglesData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnglesData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.angles.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.angles.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnglesData {
    return {
      angles: globalThis.Array.isArray(object?.angles) ? object.angles.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: AnglesData): unknown {
    const obj: any = {};
    if (message.angles?.length) {
      obj.angles = message.angles;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AnglesData>, I>>(base?: I): AnglesData {
    return AnglesData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AnglesData>, I>>(object: I): AnglesData {
    const message = createBaseAnglesData();
    message.angles = object.angles?.map((e) => e) || [];
    return message;
  },
};

function createBaseI2CScanData(): I2CScanData {
  return {};
}

export const I2CScanData: MessageFns<I2CScanData> = {
  encode(_: I2CScanData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): I2CScanData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseI2CScanData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): I2CScanData {
    return {};
  },

  toJSON(_: I2CScanData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<I2CScanData>, I>>(base?: I): I2CScanData {
    return I2CScanData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<I2CScanData>, I>>(_: I): I2CScanData {
    const message = createBaseI2CScanData();
    return message;
  },
};

function createBasePeripheralSettingsData(): PeripheralSettingsData {
  return {};
}

export const PeripheralSettingsData: MessageFns<PeripheralSettingsData> = {
  encode(_: PeripheralSettingsData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PeripheralSettingsData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeripheralSettingsData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): PeripheralSettingsData {
    return {};
  },

  toJSON(_: PeripheralSettingsData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PeripheralSettingsData>, I>>(base?: I): PeripheralSettingsData {
    return PeripheralSettingsData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeripheralSettingsData>, I>>(_: I): PeripheralSettingsData {
    const message = createBasePeripheralSettingsData();
    return message;
  },
};

function createBaseOTAStatusData(): OTAStatusData {
  return {};
}

export const OTAStatusData: MessageFns<OTAStatusData> = {
  encode(_: OTAStatusData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OTAStatusData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOTAStatusData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): OTAStatusData {
    return {};
  },

  toJSON(_: OTAStatusData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<OTAStatusData>, I>>(base?: I): OTAStatusData {
    return OTAStatusData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OTAStatusData>, I>>(_: I): OTAStatusData {
    const message = createBaseOTAStatusData();
    return message;
  },
};

function createBaseGaitData(): GaitData {
  return {};
}

export const GaitData: MessageFns<GaitData> = {
  encode(_: GaitData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GaitData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGaitData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GaitData {
    return {};
  },

  toJSON(_: GaitData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GaitData>, I>>(base?: I): GaitData {
    return GaitData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GaitData>, I>>(_: I): GaitData {
    const message = createBaseGaitData();
    return message;
  },
};

function createBaseServoStateData(): ServoStateData {
  return {};
}

export const ServoStateData: MessageFns<ServoStateData> = {
  encode(_: ServoStateData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServoStateData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServoStateData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ServoStateData {
    return {};
  },

  toJSON(_: ServoStateData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ServoStateData>, I>>(base?: I): ServoStateData {
    return ServoStateData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServoStateData>, I>>(_: I): ServoStateData {
    const message = createBaseServoStateData();
    return message;
  },
};

function createBaseServoPWMData(): ServoPWMData {
  return {};
}

export const ServoPWMData: MessageFns<ServoPWMData> = {
  encode(_: ServoPWMData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServoPWMData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServoPWMData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ServoPWMData {
    return {};
  },

  toJSON(_: ServoPWMData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ServoPWMData>, I>>(base?: I): ServoPWMData {
    return ServoPWMData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServoPWMData>, I>>(_: I): ServoPWMData {
    const message = createBaseServoPWMData();
    return message;
  },
};

function createBaseWifiSettingsData(): WifiSettingsData {
  return {};
}

export const WifiSettingsData: MessageFns<WifiSettingsData> = {
  encode(_: WifiSettingsData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WifiSettingsData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiSettingsData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): WifiSettingsData {
    return {};
  },

  toJSON(_: WifiSettingsData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<WifiSettingsData>, I>>(base?: I): WifiSettingsData {
    return WifiSettingsData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WifiSettingsData>, I>>(_: I): WifiSettingsData {
    const message = createBaseWifiSettingsData();
    return message;
  },
};

function createBaseSonarData(): SonarData {
  return {};
}

export const SonarData: MessageFns<SonarData> = {
  encode(_: SonarData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SonarData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSonarData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SonarData {
    return {};
  },

  toJSON(_: SonarData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SonarData>, I>>(base?: I): SonarData {
    return SonarData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SonarData>, I>>(_: I): SonarData {
    const message = createBaseSonarData();
    return message;
  },
};

function createBaseRSSIData(): RSSIData {
  return { rssi: 0 };
}

export const RSSIData: MessageFns<RSSIData> = {
  encode(message: RSSIData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rssi !== 0) {
      writer.uint32(8).int32(message.rssi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RSSIData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRSSIData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.rssi = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RSSIData {
    return { rssi: isSet(object.rssi) ? globalThis.Number(object.rssi) : 0 };
  },

  toJSON(message: RSSIData): unknown {
    const obj: any = {};
    if (message.rssi !== 0) {
      obj.rssi = Math.round(message.rssi);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RSSIData>, I>>(base?: I): RSSIData {
    return RSSIData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RSSIData>, I>>(object: I): RSSIData {
    const message = createBaseRSSIData();
    message.rssi = object.rssi ?? 0;
    return message;
  },
};

function createBaseSubscribeNotification(): SubscribeNotification {
  return {};
}

export const SubscribeNotification: MessageFns<SubscribeNotification> = {
  encode(_: SubscribeNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SubscribeNotification {
    return {};
  },

  toJSON(_: SubscribeNotification): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeNotification>, I>>(base?: I): SubscribeNotification {
    return SubscribeNotification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeNotification>, I>>(_: I): SubscribeNotification {
    const message = createBaseSubscribeNotification();
    return message;
  },
};

function createBaseUnsubscribeNotification(): UnsubscribeNotification {
  return {};
}

export const UnsubscribeNotification: MessageFns<UnsubscribeNotification> = {
  encode(_: UnsubscribeNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnsubscribeNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnsubscribeNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): UnsubscribeNotification {
    return {};
  },

  toJSON(_: UnsubscribeNotification): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UnsubscribeNotification>, I>>(base?: I): UnsubscribeNotification {
    return UnsubscribeNotification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnsubscribeNotification>, I>>(_: I): UnsubscribeNotification {
    const message = createBaseUnsubscribeNotification();
    return message;
  },
};

function createBaseWebsocketMessage(): WebsocketMessage {
  return {
    subNotif: undefined,
    unsubNotif: undefined,
    imu: undefined,
    imuCalibrate: undefined,
    mode: undefined,
    input: undefined,
    analytics: undefined,
    position: undefined,
    angles: undefined,
    i2cScan: undefined,
    peripheralSettings: undefined,
    otaStatus: undefined,
    gait: undefined,
    servoState: undefined,
    servoPwm: undefined,
    wifiSettings: undefined,
    sonar: undefined,
    rssi: undefined,
  };
}

export const WebsocketMessage: MessageFns<WebsocketMessage> = {
  encode(message: WebsocketMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subNotif !== undefined) {
      SubscribeNotification.encode(message.subNotif, writer.uint32(162).fork()).join();
    }
    if (message.unsubNotif !== undefined) {
      UnsubscribeNotification.encode(message.unsubNotif, writer.uint32(170).fork()).join();
    }
    if (message.imu !== undefined) {
      IMUData.encode(message.imu, writer.uint32(882).fork()).join();
    }
    if (message.imuCalibrate !== undefined) {
      IMUCalibrateData.encode(message.imuCalibrate, writer.uint32(962).fork()).join();
    }
    if (message.mode !== undefined) {
      ModeData.encode(message.mode, writer.uint32(1042).fork()).join();
    }
    if (message.input !== undefined) {
      InputData.encode(message.input, writer.uint32(1122).fork()).join();
    }
    if (message.analytics !== undefined) {
      AnalyticsData.encode(message.analytics, writer.uint32(1202).fork()).join();
    }
    if (message.position !== undefined) {
      PositionData.encode(message.position, writer.uint32(1282).fork()).join();
    }
    if (message.angles !== undefined) {
      AnglesData.encode(message.angles, writer.uint32(1362).fork()).join();
    }
    if (message.i2cScan !== undefined) {
      I2CScanData.encode(message.i2cScan, writer.uint32(1442).fork()).join();
    }
    if (message.peripheralSettings !== undefined) {
      PeripheralSettingsData.encode(message.peripheralSettings, writer.uint32(1522).fork()).join();
    }
    if (message.otaStatus !== undefined) {
      OTAStatusData.encode(message.otaStatus, writer.uint32(1602).fork()).join();
    }
    if (message.gait !== undefined) {
      GaitData.encode(message.gait, writer.uint32(1682).fork()).join();
    }
    if (message.servoState !== undefined) {
      ServoStateData.encode(message.servoState, writer.uint32(1762).fork()).join();
    }
    if (message.servoPwm !== undefined) {
      ServoPWMData.encode(message.servoPwm, writer.uint32(1842).fork()).join();
    }
    if (message.wifiSettings !== undefined) {
      WifiSettingsData.encode(message.wifiSettings, writer.uint32(1922).fork()).join();
    }
    if (message.sonar !== undefined) {
      SonarData.encode(message.sonar, writer.uint32(2002).fork()).join();
    }
    if (message.rssi !== undefined) {
      RSSIData.encode(message.rssi, writer.uint32(2082).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WebsocketMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebsocketMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.subNotif = SubscribeNotification.decode(reader, reader.uint32());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.unsubNotif = UnsubscribeNotification.decode(reader, reader.uint32());
          continue;
        }
        case 110: {
          if (tag !== 882) {
            break;
          }

          message.imu = IMUData.decode(reader, reader.uint32());
          continue;
        }
        case 120: {
          if (tag !== 962) {
            break;
          }

          message.imuCalibrate = IMUCalibrateData.decode(reader, reader.uint32());
          continue;
        }
        case 130: {
          if (tag !== 1042) {
            break;
          }

          message.mode = ModeData.decode(reader, reader.uint32());
          continue;
        }
        case 140: {
          if (tag !== 1122) {
            break;
          }

          message.input = InputData.decode(reader, reader.uint32());
          continue;
        }
        case 150: {
          if (tag !== 1202) {
            break;
          }

          message.analytics = AnalyticsData.decode(reader, reader.uint32());
          continue;
        }
        case 160: {
          if (tag !== 1282) {
            break;
          }

          message.position = PositionData.decode(reader, reader.uint32());
          continue;
        }
        case 170: {
          if (tag !== 1362) {
            break;
          }

          message.angles = AnglesData.decode(reader, reader.uint32());
          continue;
        }
        case 180: {
          if (tag !== 1442) {
            break;
          }

          message.i2cScan = I2CScanData.decode(reader, reader.uint32());
          continue;
        }
        case 190: {
          if (tag !== 1522) {
            break;
          }

          message.peripheralSettings = PeripheralSettingsData.decode(reader, reader.uint32());
          continue;
        }
        case 200: {
          if (tag !== 1602) {
            break;
          }

          message.otaStatus = OTAStatusData.decode(reader, reader.uint32());
          continue;
        }
        case 210: {
          if (tag !== 1682) {
            break;
          }

          message.gait = GaitData.decode(reader, reader.uint32());
          continue;
        }
        case 220: {
          if (tag !== 1762) {
            break;
          }

          message.servoState = ServoStateData.decode(reader, reader.uint32());
          continue;
        }
        case 230: {
          if (tag !== 1842) {
            break;
          }

          message.servoPwm = ServoPWMData.decode(reader, reader.uint32());
          continue;
        }
        case 240: {
          if (tag !== 1922) {
            break;
          }

          message.wifiSettings = WifiSettingsData.decode(reader, reader.uint32());
          continue;
        }
        case 250: {
          if (tag !== 2002) {
            break;
          }

          message.sonar = SonarData.decode(reader, reader.uint32());
          continue;
        }
        case 260: {
          if (tag !== 2082) {
            break;
          }

          message.rssi = RSSIData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WebsocketMessage {
    return {
      subNotif: isSet(object.subNotif) ? SubscribeNotification.fromJSON(object.subNotif) : undefined,
      unsubNotif: isSet(object.unsubNotif) ? UnsubscribeNotification.fromJSON(object.unsubNotif) : undefined,
      imu: isSet(object.imu) ? IMUData.fromJSON(object.imu) : undefined,
      imuCalibrate: isSet(object.imuCalibrate) ? IMUCalibrateData.fromJSON(object.imuCalibrate) : undefined,
      mode: isSet(object.mode) ? ModeData.fromJSON(object.mode) : undefined,
      input: isSet(object.input) ? InputData.fromJSON(object.input) : undefined,
      analytics: isSet(object.analytics) ? AnalyticsData.fromJSON(object.analytics) : undefined,
      position: isSet(object.position) ? PositionData.fromJSON(object.position) : undefined,
      angles: isSet(object.angles) ? AnglesData.fromJSON(object.angles) : undefined,
      i2cScan: isSet(object.i2cScan) ? I2CScanData.fromJSON(object.i2cScan) : undefined,
      peripheralSettings: isSet(object.peripheralSettings)
        ? PeripheralSettingsData.fromJSON(object.peripheralSettings)
        : undefined,
      otaStatus: isSet(object.otaStatus) ? OTAStatusData.fromJSON(object.otaStatus) : undefined,
      gait: isSet(object.gait) ? GaitData.fromJSON(object.gait) : undefined,
      servoState: isSet(object.servoState) ? ServoStateData.fromJSON(object.servoState) : undefined,
      servoPwm: isSet(object.servoPwm) ? ServoPWMData.fromJSON(object.servoPwm) : undefined,
      wifiSettings: isSet(object.wifiSettings) ? WifiSettingsData.fromJSON(object.wifiSettings) : undefined,
      sonar: isSet(object.sonar) ? SonarData.fromJSON(object.sonar) : undefined,
      rssi: isSet(object.rssi) ? RSSIData.fromJSON(object.rssi) : undefined,
    };
  },

  toJSON(message: WebsocketMessage): unknown {
    const obj: any = {};
    if (message.subNotif !== undefined) {
      obj.subNotif = SubscribeNotification.toJSON(message.subNotif);
    }
    if (message.unsubNotif !== undefined) {
      obj.unsubNotif = UnsubscribeNotification.toJSON(message.unsubNotif);
    }
    if (message.imu !== undefined) {
      obj.imu = IMUData.toJSON(message.imu);
    }
    if (message.imuCalibrate !== undefined) {
      obj.imuCalibrate = IMUCalibrateData.toJSON(message.imuCalibrate);
    }
    if (message.mode !== undefined) {
      obj.mode = ModeData.toJSON(message.mode);
    }
    if (message.input !== undefined) {
      obj.input = InputData.toJSON(message.input);
    }
    if (message.analytics !== undefined) {
      obj.analytics = AnalyticsData.toJSON(message.analytics);
    }
    if (message.position !== undefined) {
      obj.position = PositionData.toJSON(message.position);
    }
    if (message.angles !== undefined) {
      obj.angles = AnglesData.toJSON(message.angles);
    }
    if (message.i2cScan !== undefined) {
      obj.i2cScan = I2CScanData.toJSON(message.i2cScan);
    }
    if (message.peripheralSettings !== undefined) {
      obj.peripheralSettings = PeripheralSettingsData.toJSON(message.peripheralSettings);
    }
    if (message.otaStatus !== undefined) {
      obj.otaStatus = OTAStatusData.toJSON(message.otaStatus);
    }
    if (message.gait !== undefined) {
      obj.gait = GaitData.toJSON(message.gait);
    }
    if (message.servoState !== undefined) {
      obj.servoState = ServoStateData.toJSON(message.servoState);
    }
    if (message.servoPwm !== undefined) {
      obj.servoPwm = ServoPWMData.toJSON(message.servoPwm);
    }
    if (message.wifiSettings !== undefined) {
      obj.wifiSettings = WifiSettingsData.toJSON(message.wifiSettings);
    }
    if (message.sonar !== undefined) {
      obj.sonar = SonarData.toJSON(message.sonar);
    }
    if (message.rssi !== undefined) {
      obj.rssi = RSSIData.toJSON(message.rssi);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WebsocketMessage>, I>>(base?: I): WebsocketMessage {
    return WebsocketMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WebsocketMessage>, I>>(object: I): WebsocketMessage {
    const message = createBaseWebsocketMessage();
    message.subNotif = (object.subNotif !== undefined && object.subNotif !== null)
      ? SubscribeNotification.fromPartial(object.subNotif)
      : undefined;
    message.unsubNotif = (object.unsubNotif !== undefined && object.unsubNotif !== null)
      ? UnsubscribeNotification.fromPartial(object.unsubNotif)
      : undefined;
    message.imu = (object.imu !== undefined && object.imu !== null) ? IMUData.fromPartial(object.imu) : undefined;
    message.imuCalibrate = (object.imuCalibrate !== undefined && object.imuCalibrate !== null)
      ? IMUCalibrateData.fromPartial(object.imuCalibrate)
      : undefined;
    message.mode = (object.mode !== undefined && object.mode !== null) ? ModeData.fromPartial(object.mode) : undefined;
    message.input = (object.input !== undefined && object.input !== null)
      ? InputData.fromPartial(object.input)
      : undefined;
    message.analytics = (object.analytics !== undefined && object.analytics !== null)
      ? AnalyticsData.fromPartial(object.analytics)
      : undefined;
    message.position = (object.position !== undefined && object.position !== null)
      ? PositionData.fromPartial(object.position)
      : undefined;
    message.angles = (object.angles !== undefined && object.angles !== null)
      ? AnglesData.fromPartial(object.angles)
      : undefined;
    message.i2cScan = (object.i2cScan !== undefined && object.i2cScan !== null)
      ? I2CScanData.fromPartial(object.i2cScan)
      : undefined;
    message.peripheralSettings = (object.peripheralSettings !== undefined && object.peripheralSettings !== null)
      ? PeripheralSettingsData.fromPartial(object.peripheralSettings)
      : undefined;
    message.otaStatus = (object.otaStatus !== undefined && object.otaStatus !== null)
      ? OTAStatusData.fromPartial(object.otaStatus)
      : undefined;
    message.gait = (object.gait !== undefined && object.gait !== null) ? GaitData.fromPartial(object.gait) : undefined;
    message.servoState = (object.servoState !== undefined && object.servoState !== null)
      ? ServoStateData.fromPartial(object.servoState)
      : undefined;
    message.servoPwm = (object.servoPwm !== undefined && object.servoPwm !== null)
      ? ServoPWMData.fromPartial(object.servoPwm)
      : undefined;
    message.wifiSettings = (object.wifiSettings !== undefined && object.wifiSettings !== null)
      ? WifiSettingsData.fromPartial(object.wifiSettings)
      : undefined;
    message.sonar = (object.sonar !== undefined && object.sonar !== null)
      ? SonarData.fromPartial(object.sonar)
      : undefined;
    message.rssi = (object.rssi !== undefined && object.rssi !== null) ? RSSIData.fromPartial(object.rssi) : undefined;
    return message;
  },
};

type ProtoMetaMessageOptions = {
  options?: { [key: string]: any };
  fields?: { [key: string]: { [key: string]: any } };
  oneof?: { [key: string]: { [key: string]: any } };
  nested?: { [key: string]: ProtoMetaMessageOptions };
};

export interface ProtoMetadata {
  fileDescriptor: FileDescriptorProto;
  references: { [key: string]: any };
  dependencies?: ProtoMetadata[];
  options?: {
    options?: { [key: string]: any };
    services?: {
      [key: string]: { options?: { [key: string]: any }; methods?: { [key: string]: { [key: string]: any } } };
    };
    messages?: { [key: string]: ProtoMetaMessageOptions };
    enums?: { [key: string]: { options?: { [key: string]: any }; values?: { [key: string]: { [key: string]: any } } } };
  };
}

export const protoMetadata: ProtoMetadata = {
  fileDescriptor: {
    "name": "platform_shared/websocket_message.proto",
    "package": "",
    "dependency": [],
    "publicDependency": [],
    "weakDependency": [],
    "optionDependency": [],
    "messageType": [{
      "name": "IMUData",
      "field": [{
        "name": "x",
        "number": 1,
        "label": 1,
        "type": 2,
        "typeName": "",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "x",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "y",
        "number": 2,
        "label": 1,
        "type": 2,
        "typeName": "",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "y",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "z",
        "number": 3,
        "label": 1,
        "type": 2,
        "typeName": "",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "z",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "temp",
        "number": 4,
        "label": 1,
        "type": 2,
        "typeName": "",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "temp",
        "options": undefined,
        "proto3Optional": false,
      }],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "IMUCalibrateData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "ModeData",
      "field": [{
        "name": "mode",
        "number": 1,
        "label": 1,
        "type": 5,
        "typeName": "",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "mode",
        "options": undefined,
        "proto3Optional": false,
      }],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "InputData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "AnalyticsData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "PositionData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "AnglesData",
      "field": [{
        "name": "angles",
        "number": 1,
        "label": 3,
        "type": 2,
        "typeName": "",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "angles",
        "options": undefined,
        "proto3Optional": false,
      }],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "I2CScanData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "PeripheralSettingsData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "OTAStatusData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "GaitData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "ServoStateData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "ServoPWMData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "WifiSettingsData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "SonarData",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "RSSIData",
      "field": [{
        "name": "rssi",
        "number": 1,
        "label": 1,
        "type": 5,
        "typeName": "",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "rssi",
        "options": undefined,
        "proto3Optional": false,
      }],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "SubscribeNotification",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "UnsubscribeNotification",
      "field": [],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }, {
      "name": "WebsocketMessage",
      "field": [{
        "name": "sub_notif",
        "number": 20,
        "label": 1,
        "type": 11,
        "typeName": ".SubscribeNotification",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "subNotif",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "unsub_notif",
        "number": 21,
        "label": 1,
        "type": 11,
        "typeName": ".UnsubscribeNotification",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "unsubNotif",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "imu",
        "number": 110,
        "label": 1,
        "type": 11,
        "typeName": ".IMUData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "imu",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "imu_calibrate",
        "number": 120,
        "label": 1,
        "type": 11,
        "typeName": ".IMUCalibrateData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "imuCalibrate",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "mode",
        "number": 130,
        "label": 1,
        "type": 11,
        "typeName": ".ModeData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "mode",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "input",
        "number": 140,
        "label": 1,
        "type": 11,
        "typeName": ".InputData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "input",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "analytics",
        "number": 150,
        "label": 1,
        "type": 11,
        "typeName": ".AnalyticsData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "analytics",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "position",
        "number": 160,
        "label": 1,
        "type": 11,
        "typeName": ".PositionData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "position",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "angles",
        "number": 170,
        "label": 1,
        "type": 11,
        "typeName": ".AnglesData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "angles",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "i2c_scan",
        "number": 180,
        "label": 1,
        "type": 11,
        "typeName": ".I2CScanData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "i2cScan",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "peripheral_settings",
        "number": 190,
        "label": 1,
        "type": 11,
        "typeName": ".PeripheralSettingsData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "peripheralSettings",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "ota_status",
        "number": 200,
        "label": 1,
        "type": 11,
        "typeName": ".OTAStatusData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "otaStatus",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "gait",
        "number": 210,
        "label": 1,
        "type": 11,
        "typeName": ".GaitData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "gait",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "servo_state",
        "number": 220,
        "label": 1,
        "type": 11,
        "typeName": ".ServoStateData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "servoState",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "servo_pwm",
        "number": 230,
        "label": 1,
        "type": 11,
        "typeName": ".ServoPWMData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "servoPwm",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "wifi_settings",
        "number": 240,
        "label": 1,
        "type": 11,
        "typeName": ".WifiSettingsData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "wifiSettings",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "sonar",
        "number": 250,
        "label": 1,
        "type": 11,
        "typeName": ".SonarData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "sonar",
        "options": undefined,
        "proto3Optional": false,
      }, {
        "name": "rssi",
        "number": 260,
        "label": 1,
        "type": 11,
        "typeName": ".RSSIData",
        "extendee": "",
        "defaultValue": "",
        "oneofIndex": 0,
        "jsonName": "rssi",
        "options": undefined,
        "proto3Optional": false,
      }],
      "extension": [],
      "nestedType": [],
      "enumType": [],
      "extensionRange": [],
      "oneofDecl": [{ "name": "message", "options": undefined }],
      "options": undefined,
      "reservedRange": [],
      "reservedName": [],
      "visibility": 0,
    }],
    "enumType": [],
    "service": [],
    "extension": [],
    "options": undefined,
    "sourceCodeInfo": {
      "location": [{
        "path": [4, 0],
        "span": [3, 0, 8, 1],
        "leadingComments": " Individual message data types\n",
        "trailingComments": "",
        "leadingDetachedComments": [],
      }, {
        "path": [4, 18],
        "span": [32, 0, 53, 1],
        "leadingComments": " WebSocket message wrapper\n Only ONE field will be set at a time (oneof ensures this)\n",
        "trailingComments": "",
        "leadingDetachedComments": [],
      }],
    },
    "syntax": "proto3",
    "edition": 0,
  },
  references: {
    ".IMUData": IMUData,
    ".IMUCalibrateData": IMUCalibrateData,
    ".ModeData": ModeData,
    ".InputData": InputData,
    ".AnalyticsData": AnalyticsData,
    ".PositionData": PositionData,
    ".AnglesData": AnglesData,
    ".I2CScanData": I2CScanData,
    ".PeripheralSettingsData": PeripheralSettingsData,
    ".OTAStatusData": OTAStatusData,
    ".GaitData": GaitData,
    ".ServoStateData": ServoStateData,
    ".ServoPWMData": ServoPWMData,
    ".WifiSettingsData": WifiSettingsData,
    ".SonarData": SonarData,
    ".RSSIData": RSSIData,
    ".SubscribeNotification": SubscribeNotification,
    ".UnsubscribeNotification": UnsubscribeNotification,
    ".WebsocketMessage": WebsocketMessage,
  },
  dependencies: [],
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
