/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "rest_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rest_message_WifiStatus, rest_message_WifiStatus, AUTO)

PB_BIND(rest_message_WifiSettings, rest_message_WifiSettings, 2)
