/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "platform_shared/websocket_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(IMUData, IMUData, AUTO)


PB_BIND(IMUCalibrateData, IMUCalibrateData, AUTO)


PB_BIND(ModeData, ModeData, AUTO)


PB_BIND(InputData, InputData, AUTO)


PB_BIND(AnalyticsData, AnalyticsData, AUTO)


PB_BIND(PositionData, PositionData, AUTO)


PB_BIND(AnglesData, AnglesData, AUTO)


PB_BIND(I2CScanData, I2CScanData, AUTO)


PB_BIND(PeripheralSettingsData, PeripheralSettingsData, AUTO)


PB_BIND(OTAStatusData, OTAStatusData, AUTO)


PB_BIND(GaitData, GaitData, AUTO)


PB_BIND(ServoStateData, ServoStateData, AUTO)


PB_BIND(ServoPWMData, ServoPWMData, AUTO)


PB_BIND(WifiSettingsData, WifiSettingsData, AUTO)


PB_BIND(SonarData, SonarData, AUTO)


PB_BIND(RSSIData, RSSIData, AUTO)


PB_BIND(WebsocketMessage, WebsocketMessage, 2)



