name: Frontend Tests

on:
  push:
    branches: [ master ]
    paths:
        - 'app/**'  
  pull_request:
    branches: [ master ]
    paths:
        - 'app/**'  
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'pnpm'
        cache-dependency-path: './app/pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: pnpm test
